# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ParoStatus.ParoStatusXML
PackageVersion: "85.5"
InstallerLocale: de-DE
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
ExpectedReturnCodes:
- InstallerReturnCode: 32
  ReturnResponse: fileInUse
UpgradeBehavior: install
ProductCode: ParoStatusDEXML
AppsAndFeaturesEntries:
- DisplayName: ParoStatus.de XML
  Publisher: ParoStatus.de GmbH
  ProductCode: ParoStatusDEXML
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.parostatus.de/releases/85.5/Setup_x.85.5.exe
  InstallerSha256: 384F8C9B5559F6949FDD27B4D9D0E4D74501D8888548ED2749EB1B4C49E392B7
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-01
